name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt-get update

    - name: Install fmtlib
      run: sudo apt-get install -y libfmt-dev

    - name: Install nasm
      run: sudo apt-get install -y nasm

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/release -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/release --config ${{env.BUILD_TYPE}}
    
    - name: Test
      run: ${{github.workspace}}/test.sh
